# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d96e560c1123feac0b9e48da361e7de1df8ea0880acfbd0be40e3358600c21ff866bf201704525b69598501ed42813cbb51557c327cdf58e13866b409675c0e0

test:
  secret_key_base: c10af8be86fe772c9bf753fd8d25c2dc211cccedb96045335c1b419f5fda1aabac1132f8a10112e109603027eefffd178ad482390bbc8260dd2e48686adf3309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
